model_name: "unified_polypharmacy_gnn"
hidden_dim: 256
embedding_dim: 128
dropout: 0.15
num_socs: 15
num_specific: 100
optimizer:
  type: "adamw"
  lr: 0.002
  weight_decay: 0.00001
scheduler:
  type: "cosine"
  t_max: 25
batch_size: 256
epochs: 25
