import os
import json
import torch
import pandas as pd
import numpy as np
from pathlib import Path
from torch_geometric.data import HeteroData
from torch_geometric.nn import SAGEConv, to_hetero
import torch.nn as nn

# ---------------------------------------------------------
# 1. ARCHITECTURE: HETEROGENEOUS ENCODER
# ---------------------------------------------------------
class BaseGraphSAGE(nn.Module):
    def __init__(self, hidden_channels=128):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), hidden_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        return self.conv2(x, edge_index)

def create_model(metadata):
    # This automatically creates type-specific projection layers internally
    # when converting the homogeneous SAGEConv to heterogeneous using `to_hetero`
    model = BaseGraphSAGE(hidden_channels=128)
    return to_hetero(model, metadata, aggr='mean')

# ---------------------------------------------------------
# 2. MAIN LOGIC
# ---------------------------------------------------------
def main():
    print("Loading prepared datasets...")
    # These were generated by src/data/prepare_colab_graph.py
    edges_df = pd.read_parquet("data/processed/colab_primekg_safe.parquet")
    morgan_df = pd.read_parquet("data/processed/colab_morgan_features.parquet")
    
    # Discover all benchmark manifests
    manifest_paths = list(Path("artifacts/benchmarks/polypharmacy_v1").rglob("manifest.json"))
    
    # We only need to train ONE model for warm_pair, but we need 5 for cold_1 and 5 for cold_2
    # Total = 11 GraphSAGE models.
    processed_scenarios = set()
    
    for path in manifest_paths:
        with open(path, 'r') as f:
            manifest = json.load(f)
            
        scenario = manifest['scenario']
        seed = manifest['seed']
        manifest_hash = manifest['manifest_hash']
        
        # Optimization: warm_pair train drugs are identical across all seeds.
        if scenario == "warm_pair":
            if "warm_pair" in processed_scenarios:
                print(f"Skipping warm_pair seed {seed}, already trained once.")
                continue
            processed_scenarios.add("warm_pair")
            print(f"--- Training GraphSAGE for warm_pair (universal) ---")
        else:
            print(f"--- Training GraphSAGE for {scenario} seed {seed} ---")
            
        # 1. Identify validation/test drugs to exclude from training graph for cold_1 / cold_2
        # (For warm_pair, we don't exclude them because they are in the train set too)
        # TODO: Load dataset split and get train_drugs.
        # train_drugs = get_train_drugs(manifest)
        
        # 2. Build HeteroData Graph
        data = HeteroData()
        # -> DRUG nodes: feature = Morgan 2048-dim
        # -> NON-DRUG nodes: feature = constant [1.0] (1-dim)
        
        # 3. Filter edges
        # If cold_1/cold_2, remove any edge connected to a drug NOT in `train_drugs`.
        
        # 4. Train Model
        # Unsupervised Link Prediction (e.g. BPR loss with negative sampling on train edges)
        
        # 5. Inference
        # Restore full graph (but only allowed edges) to compute embeddings for ALL drugs
        
        # 6. Save embeddings
        out_path = f"artifacts/graphsage_embeddings_{manifest_hash}.parquet"
        print(f"Saved embeddings to {out_path}")

if __name__ == "__main__":
    main()
